#! /bin/bash

function main () {
    if [ "$1" = "start" ]; then start
    elif [ "$1" = "start_foreground" ]; then start_foreground
    elif [ "$1" = "stop" ]; then stop
    elif [ "$1" = "restart" ]; then restart
    elif [ "$1" = "status" ]; then status
    fi
}

# Start the server in the foreground
function start_foreground () {
    venv/bin/gunicorn -b 0.0.0.0:8001 serious_server:app
}

# Start the server
function start () {
    venv/bin/gunicorn -b 127.0.0.1:8001 serious_server:app >> server.log 2>&1 &
    status
}

# Stop the server
function stop () {
    pkill -f 'venv/bin/python venv/bin/gunicorn -b 127.0.0.1:8001 serious_server:app'
}

function restart () {
    stop
    start
}

function status () {
    pgrep -lf 'venv/bin/python venv/bin/gunicorn -b 127.0.0.1:8001 serious_server:app'
}

main $*
